[package]
name = "limited-rolling-file-appender"
version = "0.1.0"
edition = "2021"

[dependencies]
time = { version = "0.3", features = ["local-offset", "parsing", "formatting"] }
# tracing-appender = "0.2"
tracing-subscriber = "0.3"
